### ISSUE TITLE
Company doesn't work inside Org-Mode because 

### ISSUE THREAD

**Issue by Thaodan** [dakra/dmacs#4]
Hey, first of all thanks for publishing your emacs config, 
it has been very useful for me in improving my own.

I noticed that because `company-begin-commands` doesn't include 
`org-self-insert-command` (also `orgtbl-self-insert-command` in case of org tables)
the company completion popup doesn't appear inside org-mode.

Adding those to `company-begin-commmands` makes company work inside org-mode.

If this is intentional than ignore this bug.

**Comment by dakra** [comment]
Thank you very much for your comment :)

I'm not sure anymore why I even customized this var.
The default seems to be a reasonable value and also includes the org insert commands.

After having it now activated today I'm not sure I really want autocomplete in my org-mode files as it makes typing feel
a little bit slow in my large org buffers. But then I should just deactivate company in org-mode buffers instead
of changing this variable.

BTW, since switching to vertico/consult/emark I have in my todo list that I should look at replacing company with corfu+cape.
Maybe that's what I'll do next.

Thanks.

**Comment by Thaodan** [comment]
> BTW, since switching to vertico/consult/emark I have in my todo list that I should look at replacing company with corfu+cape.
> Maybe that's what I'll do next.

I've looked into those too now that I looked at cape it seems amazing.
Just need to look how to replace some of the company extensions such as company-emojify.

>After having it now activated today I'm not sure I really want autocomplete in my org-mode files as it makes typing feel
a little bit slow in my large org buffers. But then I should just deactivate company in org-mode buffers instead
of changing this variable.

It may make sense to only activate certain backends in org-mode buffers.

PS: Your repo was a great inspiration but how you not share those parts of your config you are not allowed to share? I've looked into your org-mode setup where you sync your agenda with the bugtrackers you use. Have you experience of doing the same with  bugzilla?

**Comment by dakra** [comment]
> how you not share those parts of your config you are not allowed to share?

I have it a bit messy right now. In general I try to get auth-token/credentials etc all from `~/.authinfo.gpg`
but I have still plenty of username stuff (e.g. my mailbox names/email addresses etc) that are not really private/secret
but also shouldn't be in this repo. Additionally I have a private branch with stuff not committed to the public master.
Another thing on my todo-list since forever is to refactor all this private information in a separate e.g. `private.el` file
and then just `(load "private.el)` or something like that.

> I've looked into your org-mode setup where you sync your agenda with the bugtrackers you use. Have you experience of doing the same with bugzilla?

Unfortunately not.
I have only custom code for github or jira to org.
It's also 1-way only, so not like some other more sophisticated solutions (ejira) that sync org modifications back again.
Almost always I only need the ticket once to track my time and what I comment etc is different from what
I write in my personal org files under the ticket.

**Comment by Thaodan** [comment]
> Another thing on my todo-list since forever is to refactor all this private information in a separate e.g. `private.el` file
> and then just `(load "private.el)` or something like that.

Hey, 

I've actually come up with a solution that would allow you to keep your existing setup without using something like `(load "private.el"` but by using Org-Mode noweb syntax and some org-babel-tangle-file wrapper.

Doing so allowed me to finally publish my configuration that I based up on yours.

The section "Private init" inside my init.org explains how to insert the private information that replaces the noweb references at compile time:
[Thaodan/emacs.d/readme.org/Private  Init](https://github.com/Thaodan/emacs.d/?tab=readme-ov-file#private-init)

The references work quite well except in cases where part of the setting is public and part of the setting is not. In such cases I create a copy of the original variable such as `org-link-abbrev-alist` -> `org-link-abbrev-alist-private` and combine the two at runtime. 

The support for include in `org-babel-tangle-file` is added using this advice function:
https://github.com/Thaodan/emacs.d/blob/master/etc/borg/init.el#L17

The file containing the function  is loaded by telling Borg to also load Borg's init.el when tangling init.el:
https://github.com/Thaodan/emacs.d/blob/master/etc/borg/config.mk#L5
